### ISSUE TITLE
Graphics are severely distorted

### ISSUE THREAD

**Issue by denjhang** [slu4coder/Minimal-Terminal#4]
I've successfully made a Minimal terminal, but I'm finding that the vga output is sporadic and distorted. And it seems that the PS2 keyboard is typing certain characters automatically.
![8C06F78830BA9AAB8A668AC20CCF6721](https://user-images.githubusercontent.com/61811583/169773064-e4579d83-28e6-4748-86c0-9373956010a3.png)

![9439A317C21FBE571A014AA651523607](https://user-images.githubusercontent.com/61811583/169773075-3b48253f-1738-4cf4-9108-559d2b7f78d3.png)

**Comment by abaffa** [comment]
whats the clock speed u're using?

**Comment by denjhang** [comment]
I use a 24.000mhz passive crystal. I checked other issues on github that inspired me. So I used a 24mhz active crystal oscillator and everything was fine.

**Comment by abaffa** [comment]
yep... new atmega328s cannot drive 24mhz... I've tested 24, 20 16 mhz passive crystals but only 16mhz works. 
So... only active crystals can be now used to overclock the atmega328.

**Comment by slu4coder** [comment]
The ATMega328s I had used for development and testing were indeed a couple of years old. I've never had any problems with overclocking them up to 24MHz passively. Anyway, thanks for digging into this, guys. This can be a valuable information for anyone rebuilding this little terminal.
Cheers, slu4
