### ISSUE TITLE
Uart chip inactive without keyboard attached

### ISSUE THREAD

**Issue by MRjimbob81** [slu4coder/Minimal-Terminal#5]
Hello,

Looks like the UART/PS2 processor is in a constant wait state (or crashed) if no keyboard is attached to the PS2 port on initial startup. 
This will not allow any UART traffic to pass through to the VGA processor to be displayed on screen. eg: a keyboard-less terminal.

**Comment by slu4coder** [comment]
Hi,
I cannot confirm or reproduce this behavior on my hardware. Powering up the terminal without PS/2 keyboard attached leaves my Minimal Terminal running just fine and displaying received characters.

**Comment by MRjimbob81** [comment]
Looks like this issue was my own stupidity. I burn'ed a forked image to the UART/PS2 processor and not the original one. Both files have the same file name... 

My apologies.
